apiVersion: v1
kind: Service
metadata:
  name: dc-front
  labels:
    app: dc-front
spec:
  selector:
    app: dc-front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: 8084-tcp